### ISSUE TITLE
Speedup Wharf

### ISSUE THREAD

**Issue by bluecivet** [ZOSOpenTools/wharf#40]
One reason for Wharf being slow could be that it relies on the go list command.
```
exec.Command("go list")
```
It lists the package dependencies, but this operation is expensive and requires finding an alternative method.
One option could be to use the package loading function, which appears to integrate the functionality of the go list command into the code.
https://pkg.go.dev/golang.org/x/tools@v0.19.0/go/packages

**Comment by bluecivet** [comment]
After reviewing the code implementation at https://pkg.go.dev/golang.org/x/tools@v0.19.0/go/packages, it was observed that they also utilize exec.Command to execute the 'go list' command, as shown in https://cs.opensource.google/go/x/tools/+/refs/tags/v0.19.0:internal/gocommand/invoke.go.

**Comment by MacMalainey** [comment]
Fixed (behind new build tag `wharf_refactor`) as of #52
