### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by IgorTodorovskiIBM** [ZOSOpenTools/wharf#9]
1. Can wharf be simplified further to automatically initialize the workspace? Is this possible?
2. Providing an example (or example repo) would be useful to understand the right sequence of commands as well as the required directory structure
3. As noted before, git initializing the packages using `git init && git add .` would be useful so that we can see the diffs applied by wharf.

Once I get past the `github.ibm.com/open-z/wharf/internal/packages.loadBuildConfigs` issue, I'll provide more feedback.

**Comment by MacMalainey** [comment]
Done
